---
# package.yaml
#  >> Index dei pacchetti nxget
#  Ultimo Update: 01/07/2021 ore 20:03
#  N° di pacchetti disponibili: 23
- nome: 7zip
  id: 7zip
  idx: .p01
  versione: v21.02
  repository: nxget
  manifest: https://raw.githubusercontent.com/vlT-vl/nxget/master/manifest/nxget/7zip.yaml
- nome: Adobe Reader DC
  id: adobereaderdc
  idx: .p02
  versione: v19.008.20071
  repository: nxget
  manifest: https://raw.githubusercontent.com/vlT-vl/nxget/master/manifest/nxget/adobereaderdc.yaml
- nome: Atom
  id: atom
  idx: .p03
  versione: v1.57.0
  repository: nxget
  manifest: https://raw.githubusercontent.com/vlT-vl/nxget/master/manifest/nxget/atom.yaml
- nome: Expandrive
  id: expandrive
  idx: .p04
  versione: v2021.6.4
  repository: nxget
  manifest: https://raw.githubusercontent.com/vlT-vl/nxget/master/manifest/nxget/expandrive.yaml
- nome: Google Chrome
  id: chrome
  idx: .p05
  versione: LTS
  repository: nxget
  manifest: https://raw.githubusercontent.com/vlT-vl/nxget/master/manifest/nxget/googlechrome.yaml
- nome: Lenovo System Update
  id: lenovosystemupdate
  idx: .p06
  versione: v5.07.0124
  repository: nxget
  manifest: https://raw.githubusercontent.com/vlT-vl/nxget/master/manifest/nxget/lenovosystemupdate.yaml
- nome: Node.js
  id: node
  idx: .p07
  versione: v16.4.1
  repository: nxget
  manifest: https://raw.githubusercontent.com/vlT-vl/nxget/master/manifest/nxget/nodejs.yaml
- nome: Notepad++
  id: notepadpp
  idx: .p08
  versione: v8.1
  repository: nxget
  manifest: https://raw.githubusercontent.com/vlT-vl/nxget/master/manifest/nxget/notepadpp.yaml
- nome: Office365
  id: office365
  idx: .p09
  versione: v16.0.14131.20278
  repository: nxget
  manifest: https://raw.githubusercontent.com/vlT-vl/nxget/master/manifest/nxget/office365.yaml
- nome: BitWarden
  id: bitwarden
  idx: .p10
  versione: v1.27.0
  repository: nxget
  manifest: https://raw.githubusercontent.com/vlT-vl/nxget/master/manifest/nxget/bitwarden.yaml
- nome: Skype
  id: skype
  idx: .p11
  versione: v8.72.0.94
  repository: nxget
  manifest: https://raw.githubusercontent.com/vlT-vl/nxget/master/manifest/nxget/skype.yaml
- nome: Spotify
  id: spotify
  idx: .p12
  versione: LTS
  repository: nxget
  manifest: https://raw.githubusercontent.com/vlT-vl/nxget/master/manifest/nxget/spotify.yaml
- nome: VLC
  id: vlc
  idx: .p13
  versione: v3.0.12
  repository: nxget
  manifest: https://raw.githubusercontent.com/vlT-vl/nxget/master/manifest/nxget/vlc.yaml
- nome: WhatsApp
  id: whatsapp
  idx: .p14
  versione: LTS
  repository: nxget
  manifest: https://raw.githubusercontent.com/vlT-vl/nxget/master/manifest/nxget/whatsapp.yaml
- nome: Windows Terminal
  id: windowsterminal
  idx: .p15
  versione: v1.8.1444.0
  repository: nxget
  manifest: https://raw.githubusercontent.com/vlT-vl/nxget/master/manifest/nxget/windowsterminal.yaml
- nome: Windows Package Manager
  id: winget
  idx: .p16
  versione: v0.3.11201-preview
  repository: nxget
  manifest: https://raw.githubusercontent.com/vlT-vl/nxget/master/manifest/nxget/winget.yaml
- nome: Visual C++ 2015-2019 Redistributable x86
  id: vcredist19x86
  idx: .p17
  versione: v2015-2019x86
  repository: nxget
  manifest: https://raw.githubusercontent.com/vlT-vl/nxget/master/manifest/nxget/vcredist19x86.yaml
- nome: Visual C++ 2015-2019 Redistributable x64
  id: vcredist19x64
  idx: .p18
  versione: v2015-2019x64
  repository: nxget
  manifest: https://raw.githubusercontent.com/vlT-vl/nxget/master/manifest/nxget/vcredist19x64.yaml
- nome: Visual C++ 2013 Redistributable x86
  id: vcredist13x86
  idx: .p19
  versione: v2013x86
  repository: nxget
  manifest: https://raw.githubusercontent.com/vlT-vl/nxget/master/manifest/nxget/vcredist13x86.yaml
- nome: Visual C++ 2013 Redistributable x64
  id: vcredist13x64
  idx: .p20
  versione: v2013x64
  repository: nxget
  manifest: https://raw.githubusercontent.com/vlT-vl/nxget/master/manifest/nxget/vcredist13x64.yaml
- nome: TeamViewer HOST
  id: twhost
  idx: .p21
  versione: v15.17.7.0
  repository: nxget
  manifest: https://raw.githubusercontent.com/vlT-vl/nxget/master/manifest/nxget/teamviewerhost.yaml
- nome: Python
  id: python
  idx: .p22
  versione: v2.17.18
  repository: nxget
  manifest: https://raw.githubusercontent.com/vlT-vl/nxget/master/manifest/nxget/python.yaml
- nome: Netwide Assembler (NASM)
  id: nasm
  idx: .p23
  versione: v2.15.05
  repository: nxget
  manifest: https://raw.githubusercontent.com/vlT-vl/nxget/master/manifest/nxget/nasm.yaml
