---
# package.yaml
#  >> Index dei pacchetti nxget
#  ultimoupdate: 03/09/2020 ore 15:34
#
- nome: 7zip
  id: 7zip
  pkgidx: .p1
  versione: v19.00
  repository: nxget
  manifest: https://raw.githubusercontent.com/vlT-vl/nxget/master/manifest/nxget/7zip.yaml
- nome: Adobe Reader DC
  id: adobereaderdc
  pkgidx: .p2
  versione: v19.008.20071
  repository: nxget
  manifest: https://raw.githubusercontent.com/vlT-vl/nxget/master/manifest/nxget/adobereaderdc.yaml
- nome: Atom
  id: atom
  pkgidx: .p3
  versione: v1.50.0
  repository: nxget
  manifest: https://raw.githubusercontent.com/vlT-vl/nxget/master/manifest/nxget/atom.yaml
- nome: Dashlane
  id: dashlane
  pkgidx: .p4
  versione: v6.2033.0.38021
  repository: nxget
  manifest: https://raw.githubusercontent.com/vlT-vl/nxget/master/manifest/nxget/dashlane.yaml
