---
# package.yaml
#  >> Index dei pacchetti nxget
#  Ultimo Update: 22/10/2020 ore 10:05
#  N° di pacchetti disponibili: 17
# 
- nome: 7zip
  id: 7zip
  idx: .p01
  versione: v19.00
  repository: nxget
  manifest: https://raw.githubusercontent.com/vlT-vl/nxget/master/manifest/nxget/7zip.yaml
- nome: Adobe Reader DC
  id: adobereaderdc
  idx: .p02
  versione: v19.008.20071
  repository: nxget
  manifest: https://raw.githubusercontent.com/vlT-vl/nxget/master/manifest/nxget/adobereaderdc.yaml
- nome: Atom
  id: atom
  idx: .p03
  versione: v1.52.0
  repository: nxget
  manifest: https://raw.githubusercontent.com/vlT-vl/nxget/master/manifest/nxget/atom.yaml
- nome: Edge
  id: edge
  idx: .p04
  versione: LTS
  repository: nxget
  manifest: https://raw.githubusercontent.com/vlT-vl/nxget/master/manifest/nxget/edge.yaml
- nome: Expandrive
  id: expandrive
  idx: .p05
  versione: v7.6.5
  repository: nxget
  manifest: https://raw.githubusercontent.com/vlT-vl/nxget/master/manifest/nxget/expandrive.yaml
- nome: Google Chrome
  id: chrome
  idx: .p06
  versione: LTS
  repository: nxget
  manifest: https://raw.githubusercontent.com/vlT-vl/nxget/master/manifest/nxget/googlechrome.yaml
- nome: Lenovo System Update
  id: lenovosystemupdate
  idx: .p07
  versione: v5.07.0110
  repository: nxget
  manifest: https://raw.githubusercontent.com/vlT-vl/nxget/master/manifest/nxget/lenovosystemupdate.yaml
- nome: Node.js
  id: nodejs
  idx: .p08
  versione: v15.0.0
  repository: nxget
  manifest: https://raw.githubusercontent.com/vlT-vl/nxget/master/manifest/nxget/nodejs.yaml
- nome: Notepad++
  id: notepadpp
  idx: .p09
  versione: v7.8.9
  repository: nxget
  manifest: https://raw.githubusercontent.com/vlT-vl/nxget/master/manifest/nxget/notepadpp.yaml
- nome: Office365
  id: office365
  idx: .p10
  versione: v7.8.9
  repository: nxget
  manifest: https://raw.githubusercontent.com/vlT-vl/nxget/master/manifest/nxget/office365.yaml
- nome: 1Password
  id: 1password
  idx: .p11
  versione: v7.6.785
  repository: nxget
  manifest: https://raw.githubusercontent.com/vlT-vl/nxget/master/manifest/nxget/onepassword.yaml
- nome: Skype
  id: skype
  idx: .p12
  versione: LTS
  repository: nxget
  manifest: https://raw.githubusercontent.com/vlT-vl/nxget/master/manifest/nxget/skype.yaml
- nome: Spotify
  id: spotify
  idx: .p13
  versione: LTS
  repository: nxget
  manifest: https://raw.githubusercontent.com/vlT-vl/nxget/master/manifest/nxget/spotify.yaml
- nome: VLC
  id: vlc
  idx: .p14
  versione: v3.0.11
  repository: nxget
  manifest: https://raw.githubusercontent.com/vlT-vl/nxget/master/manifest/nxget/vlc.yaml
- nome: WhatsApp
  id: whatsapp
  idx: .p15
  versione: LTS
  repository: nxget
  manifest: https://raw.githubusercontent.com/vlT-vl/nxget/master/manifest/nxget/whatsapp.yaml
- nome: --------------------
  id: ---
  idx: ---
  versione: --------
  repository: ------
  manifest: ------
- nome: TightVNC
  id: tightvncfla
  idx: .f01
  versione: LTS
  repository: fla
  manifest: https://raw.githubusercontent.com/vlT-vl/nxget/master/manifest/fla/tightvnc.yaml
